# Protocol plugin build support.
#
# A plugin is written once against protocol/IProtocolPlugin.h and can be built
# either as a runtime-loadable MODULE (QPluginLoader picks it up from
# bin/plugins) or linked straight into the application. The only difference on
# the source side is the HWSIM_PLUGIN_STATIC_BUILD definition, which the
# HWSIM_DECLARE_PROTOCOL_PLUGIN macro uses to decide between emitting Qt plugin
# metadata and emitting a static factory symbol.
#
#   hwsim_add_protocol_plugin(
#       NAME       modbus
#       CLASS_NAME ModbusPlugin          # unqualified, as Qt writes it into the metadata
#       SOURCES    ModbusPlugin.cpp ...
#       DEPS       hwsim::simulator
#       LINKAGE    DEFAULT|DYNAMIC|STATIC   # optional, defaults to HWSIM_PLUGIN_LINKAGE
#   )

define_property(GLOBAL PROPERTY HWSIM_STATIC_PLUGINS
    BRIEF_DOCS "Plugins linked into the application"
    FULL_DOCS  "Plugin ids whose factory symbol must be referenced by the generated import file")
define_property(GLOBAL PROPERTY HWSIM_DYNAMIC_PLUGINS
    BRIEF_DOCS "Plugins built as loadable modules"
    FULL_DOCS  "Plugin ids discovered at runtime by scanning the plugin directory")

function(hwsim_add_protocol_plugin)
    cmake_parse_arguments(ARG "" "NAME;LINKAGE;CLASS_NAME" "SOURCES;DEPS" ${ARGN})

    if(NOT ARG_NAME)
        message(FATAL_ERROR "hwsim_add_protocol_plugin: NAME is required")
    endif()
    if(NOT ARG_SOURCES)
        message(FATAL_ERROR "hwsim_add_protocol_plugin(${ARG_NAME}): SOURCES is required")
    endif()

    set(_linkage "${ARG_LINKAGE}")
    if(NOT _linkage OR _linkage STREQUAL "DEFAULT")
        set(_linkage "${HWSIM_PLUGIN_LINKAGE}")
    endif()

    # Per-plugin override, e.g. -DHWSIM_PLUGIN_MODBUS_LINKAGE=STATIC
    string(TOUPPER "${ARG_NAME}" _upper)
    if(DEFINED HWSIM_PLUGIN_${_upper}_LINKAGE)
        set(_linkage "${HWSIM_PLUGIN_${_upper}_LINKAGE}")
    endif()

    set(_target "hwsim_plugin_${ARG_NAME}")

    if(_linkage STREQUAL "STATIC")
        # Plain static library rather than qt_add_plugin(STATIC): the framework
        # discovers static plugins through its own factory symbols, so Qt's
        # Q_IMPORT_PLUGIN machinery would only add a second, redundant path.
        add_library(${_target} STATIC ${ARG_SOURCES})
        target_compile_definitions(${_target} PRIVATE HWSIM_PLUGIN_STATIC_BUILD)
        set_property(GLOBAL APPEND PROPERTY HWSIM_STATIC_PLUGINS "${ARG_NAME}")
    elseif(_linkage STREQUAL "DYNAMIC")
        # SHARED, not MODULE: qt_add_plugin only accepts SHARED or STATIC, and
        # SHARED is what makes it emit a CMake MODULE library, which is the
        # right kind for something loaded through QPluginLoader.
        set(_class_name_args "")
        if(ARG_CLASS_NAME)
            set(_class_name_args CLASS_NAME ${ARG_CLASS_NAME})
        endif()

        qt_add_plugin(${_target} SHARED ${_class_name_args} ${ARG_SOURCES})

        set_target_properties(${_target} PROPERTIES
            LIBRARY_OUTPUT_DIRECTORY "${HWSIM_PLUGIN_OUTPUT_DIR}"
            RUNTIME_OUTPUT_DIRECTORY "${HWSIM_PLUGIN_OUTPUT_DIR}")
        foreach(_cfg IN ITEMS DEBUG RELEASE RELWITHDEBINFO MINSIZEREL)
            set_target_properties(${_target} PROPERTIES
                LIBRARY_OUTPUT_DIRECTORY_${_cfg} "${HWSIM_PLUGIN_OUTPUT_DIR}"
                RUNTIME_OUTPUT_DIRECTORY_${_cfg} "${HWSIM_PLUGIN_OUTPUT_DIR}")
        endforeach()
        set_property(GLOBAL APPEND PROPERTY HWSIM_DYNAMIC_PLUGINS "${ARG_NAME}")
    else()
        message(FATAL_ERROR "hwsim_add_protocol_plugin(${ARG_NAME}): unknown LINKAGE '${_linkage}'")
    endif()

    target_include_directories(${_target}
        PRIVATE ${CMAKE_SOURCE_DIR}/src ${CMAKE_CURRENT_SOURCE_DIR})

    target_link_libraries(${_target} PRIVATE
        hwsim::cpp20
        hwsim::core
        hwsim::protocol
        ${ARG_DEPS})

    set_target_properties(${_target} PROPERTIES
        AUTOMOC ON
        CXX_STANDARD 20
        CXX_STANDARD_REQUIRED ON
        CXX_EXTENSIONS OFF
        FOLDER "plugins")

    hwsim_set_target_warnings(${_target})
endfunction()


# Emits the translation unit that wires statically linked plugins into the
# PluginManager. Produces an empty registration function when every plugin is
# dynamic, so the application code path stays identical either way.
function(hwsim_generate_static_plugin_imports out_var)
    get_property(_plugins GLOBAL PROPERTY HWSIM_STATIC_PLUGINS)

    set(_decls "")
    set(_calls "")
    foreach(_p IN LISTS _plugins)
        string(APPEND _decls "extern \"C\" QObject* hwsim_static_plugin_${_p}();\n")
        string(APPEND _calls "    manager.addStaticPlugin(QStringLiteral(\"${_p}\"), &hwsim_static_plugin_${_p});\n")
    endforeach()

    set(_content
"// Generated by hwsim_generate_static_plugin_imports(). Do not edit.
#include <protocol/PluginManager.h>

#include <QObject>
#include <QString>

${_decls}
namespace hwsim::protocol {

void registerStaticPlugins(PluginManager& manager)
{
${_calls}    Q_UNUSED(manager)
}

} // namespace hwsim::protocol
")

    set(_path "${CMAKE_CURRENT_BINARY_DIR}/StaticPluginImports.cpp")
    file(GENERATE OUTPUT "${_path}" CONTENT "${_content}")
    set(${out_var} "${_path}" PARENT_SCOPE)
endfunction()


# Plugin targets are declared after the app in some configurations; the caller
# must therefore add the plugin subdirectory before invoking the generator.
function(hwsim_link_static_plugins target)
    get_property(_plugins GLOBAL PROPERTY HWSIM_STATIC_PLUGINS)
    foreach(_p IN LISTS _plugins)
        target_link_libraries(${target} PRIVATE hwsim_plugin_${_p})
    endforeach()
endfunction()
